name: precompile
url: http://precompile.com
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: [footnotes]

keywords: "Dirk Gadsden, software engineering, web development, programming, C, Ruby, JavaScript"
