name: precompile
url: https://precompile.com
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# redcarpet:
#   extensions: [footnotes]

keywords: "Dirk Gadsden, software engineering, web development, programming, C, Ruby, JavaScript"
